spring.application.name=aiDoc

jwt.secret=${JWT_SECRET}

spring.datasource.url=${SPRING_DATASOURCE_URL}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.properties.hibernate.default_schema=auth

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}


spring.kafka.consumer.group-id=ai-doc-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# ? CRITICAL (otherwise deserialization fails)
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# ? VERY IMPORTANT (tells Kafka what object to map to)
spring.kafka.consumer.properties.spring.json.value.default.type=com.aaron.aiDoc.Kafka.DocumentEvent


embedding.model=nomic-embed-text

spring.ai.ollama.base-url=${SPRING_AI_OLLAMA_BASE_URL}

spring.ai.ollama.chat.options.model=phi3:mini
spring.ai.ollama.chat.options.temperature=0.2
